name: "Check Labels"

on:
  pull_request:

jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Parsing labels
        run: |
          labels_in_pr=${{ github.event.pull_request.labels.*.name }}
          echo "Size of array: ${{labels_in_pr[@]}}"
