name: "Check Labels"

on:
  pull_request:

jobs:
  get_labels:
    name: Getting Labels
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo "::set-output name=value::${{ github.event.pull_request.labels.*.name }}"
  run_label_check:
    needs: [ get_labels ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.get_labels.outputs.matrix) }}
    steps:
      - id: run_label
        run: |
          echo "${{ matrix.value }}"
