name: "Check Labels"

on:
  pull_request:

jobs:
  list_of_labels:
    name: Listing labels
    runs-on: ubuntu-latest
    steps:
      - name: Listing
        run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
  get_modified_files:
    name: Get Modified Files
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
  list_of_labels_v2:
    name: Listing labels v2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Listing v2
        env:
          LIST_LABEL: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          list_length=$(echo "$LIST_LABEL" | jq length)
          list_length=$((list_length - 1))
          for i in `seq 0 $list_length`; do
            module=$(echo "$LIST_LABEL" | jq .["$i"] | cut -d "\"" -f 2)
            echo "Module: $module"

            command_result=$(find . -name "${module}")
            if [ -z "$command_result" ]; then
              echo "NOT FOUND"
            else
              echo "FOUND"
            fi
          done
          git branch
          mapfile -t changed_files < <(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          printf 'changed file: %s\n' ${changed_files[*]}
          echo "---> END <---"
  get_labels:
    name: Getting Labels
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.value }}
    steps:
      - id: set-matrix
        run: |
          echo "::set-output name=value::${{ toJson(github.event.pull_request.labels.*.name) }}"
  run_label_check:
    needs: get_labels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value:
          - ${{fromJson(needs.get_labels.outputs.matrix)}}
    steps:
      - id: run_label
        run: |
          echo ${{ matrix.value }}
