name: "Check Labels"

on:
  pull_request:

jobs:
  list_of_labels:
    name: Listing labels
    runs-on: ubuntu-latest
    steps:
      - name: Listing
        run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
  list_of_labels_v2:
    name: Listing labels v2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Listing v2
        env:
          LIST_LABEL: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          for i in ${!LIST_LABEL[@]}; do
            echo "element $i is ${LIST_LABEL[$i]}"
          done
          echo "$LIST_LABEL" | jq
          echo "$LIST_LABEL" | jq length
          list_length=$(echo "$LIST_LABEL" | jq length)
          echo "-> $list_length"
          list_length=$((list_length - 1))
          echo "--> $list_length"
          for i in `seq 0 $list_length`; do
            echo "For loop [${i}]"
            module=$(echo "$LIST_LABEL" | jq .["$i"] | cut -d "\"" -f 2)
            echo "Module: $module"
            ls
            ls "${module}" 2>/dev/null
            command_result=$?
            echo "Result -> $command_result"
            if [ "$command_result" -gt 0 ]; then
              echo "NOT FOUND"
            else
              echo "FOUND"
            fi
          done
  get_labels:
    name: Getting Labels
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.value }}
    steps:
      - id: set-matrix
        run: |
          echo "::set-output name=value::${{ toJson(github.event.pull_request.labels.*.name) }}"
  run_label_check:
    needs: get_labels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value:
          - ${{fromJson(needs.get_labels.outputs.matrix)}}
    steps:
      - id: run_label
        run: |
          echo ${{ matrix.value }}
