name: "Check Labels"

on:
  pull_request:

jobs:
  list_of_labels:
    name: List labels
    runs-on: ubuntu-latest
    steps:
      - name: Print labels from PR
        run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
  get_modified_files:
    needs: [list_of_labels]
    name: Get Modified Files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.file_changes.outputs.value }}
    steps:
      - name: Init
        id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - env:
          LIST_OF_CHANGED_FILES:  ${{ steps.file_changes.outputs.files}}
        run: |
          var_one=$(echo  $LIST_OF_CHANGED_FILES | jq )
          echo "::set-output name=value::${var_one}"
          echo "Print raw 1"
          echo '${{ steps.file_changes.outputs.files}}'
          echo "Print raw 2 (LIST_OF_CHANGED_FILES)"
          echo "$LIST_OF_CHANGED_FILES"
          echo "Print jq"
          echo "${var_one}"
          echo "END 66"
  list_of_labels_v2:
    needs: [list_of_labels, get_modified_files]
    name: Listing labels v2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Listing v2
        env:
          LIST_LABEL: ${{ toJson(github.event.pull_request.labels.*.name) }}
          LIST_OF_CHANGED_FILES:  ${{ steps.file_changes.outputs.files}}
        run: |
          list_length=$(echo "$LIST_LABEL" | jq length)
          list_length=$((list_length - 1))
          for i in `seq 0 $list_length`; do
            module=$(echo "$LIST_LABEL" | jq .["$i"] | cut -d "\"" -f 2)
            echo "Module: $module"

            command_result=$(find . -name "${module}")
            if [ -z "$command_result" ]; then
              echo "NOT FOUND"
            else
              echo "FOUND"
            fi
          done
          git branch
          mapfile -t changed_files < <(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          printf 'changed file: %s\n' ${changed_files[*]}
          echo "---> END <---"
          echo ${LIST_OF_CHANGED_FILES}
          echo "---> END2 <---"
  get_labels:
    needs: [list_of_labels, get_modified_files, list_of_labels_v2]
    name: Getting Labels
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.value }}
    steps:
      - id: set_matrix
        run: |
          echo "::set-output name=value::${{ toJson(github.event.pull_request.labels.*.name) }}"
  run_label_check:
    needs: [list_of_labels, get_modified_files, list_of_labels_v2, get_labels]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value:
          - ${{fromJson(needs.get_labels.outputs.matrix)}}
    steps:
      - id: run_label
        run: |
          echo ${{ matrix.value }}
