name: "Check Labels"

on:
  pull_request:

jobs:
  list_of_labels:
    name: Listing labels
    runs-on: ubuntu-latest
    steps:
      - name: Listing
        run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
  list_of_labels_v2:
    name: Listing labels v2
    runs-on: ubuntu-latest
    steps:
      - name: Listing v2
        env: 
          LIST_LABEL: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          echo "V2"
          echo "$LIST_LABEL"
  get_labels:
    name: Getting Labels
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.value }}
    steps:
      - id: set-matrix
        run: |
          echo "::set-output name=value::${{ toJson(github.event.pull_request.labels.*.name) }}"
  run_label_check:
    needs: get_labels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value:
          - ${{fromJson(needs.get_labels.outputs.matrix)}}
    steps:
      - id: run_label
        run: |
          echo ${{ matrix.value }}
