name: Main Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build APK
        run: bash ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apkfile
          path: app/build/outputs/apk/debug/app-debug.apk
  secrets:
    name: Testing screts
    runs-on: ubuntu-latest
    steps:
      - name: Secrets
        run: echo "[${{ secrets.TOKEN_ONE }}]"
      - name: Scrects2
        run: ${{ secrets.ECHO_VAR }}
      - name: Secrets3
        run: find . -name ${{ secrets.FIND_SE }}
      - name: Secrets4
        run: echo "The API key is:${{secrets.API_KEY}}"
